name: Waka Readme

on:
  schedule:
    # Runs at 18:30 Beijing Time (UTC+8)
    - cron: '30 10 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: 'zh-Hans'
          SHOW_LINES_OF_CODE: "True"
          SHOW_SHORT_INFO: "Flase"
