name: Waka Readme

on:
  schedule:
    # 每天北京时间 18:30 执行
    - cron: '30 10 * * *'
  # 允许手动执行workflow
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master    
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
